complete -c rome -f
complete -c rome -n '__fish_use_subcommand' -a 'start' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'develop' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'stop' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'run' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'restart' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'status' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'lsp' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a '_evict' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a '_moduleSignature' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a '_projectDump' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'analyzeDependencies' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'bundle' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'cache dir' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'cache clear' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'check' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'ci' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'compile' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'config location' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'config disable' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'config enable' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'config push' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'config set' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'config set-directory' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'format' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'init' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'json' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'noop' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'parse' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'publish' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'resolve' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'test' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'recover apply' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'recover clear' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'recover diff' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'recover dir' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'recover list' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'recover pop' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'rage' -d '[object Object]'
complete -c rome -n '__fish_use_subcommand' -a 'logs' -d '[object Object]'
complete -c rome  -l 'version'
complete -c rome  -l 'writeShellCompletions'
complete -c rome -n '__fish_seen_subcommand_from _projectDump' -l 'complete'
complete -c rome -n '__fish_seen_subcommand_from analyzeDependencies' -l 'compact'
complete -c rome -n '__fish_seen_subcommand_from analyzeDependencies' -l 'focusSource'
complete -c rome -n '__fish_seen_subcommand_from bundle' -l 'quiet'
complete -c rome -n '__fish_seen_subcommand_from check' -l 'apply'
complete -c rome -n '__fish_seen_subcommand_from check' -l 'formatOnly'
complete -c rome -n '__fish_seen_subcommand_from check' -l 'changed'
complete -c rome -n '__fish_seen_subcommand_from ci' -l 'fix'
complete -c rome -n '__fish_seen_subcommand_from compile' -l 'bundle'
complete -c rome -n '__fish_seen_subcommand_from config location' -l 'user'
complete -c rome -n '__fish_seen_subcommand_from config disable' -l 'user'
complete -c rome -n '__fish_seen_subcommand_from config enable' -l 'user'
complete -c rome -n '__fish_seen_subcommand_from config push' -l 'user'
complete -c rome -n '__fish_seen_subcommand_from config set' -l 'user'
complete -c rome -n '__fish_seen_subcommand_from config set-directory' -l 'user'
complete -c rome -n '__fish_seen_subcommand_from format' -l 'allowDiagnostics'
complete -c rome -n '__fish_seen_subcommand_from init' -l 'apply'
complete -c rome -n '__fish_seen_subcommand_from init' -l 'allowDirty'
complete -c rome -n '__fish_seen_subcommand_from noop' -l 'hang'
complete -c rome -n '__fish_seen_subcommand_from parse' -l 'allowDiagnostics'
complete -c rome -n '__fish_seen_subcommand_from parse' -l 'compact'
complete -c rome -n '__fish_seen_subcommand_from parse' -l 'sourceType'
complete -c rome -n '__fish_seen_subcommand_from test' -l 'filter'
complete -c rome -n '__fish_seen_subcommand_from test' -l 'coverage'
complete -c rome -n '__fish_seen_subcommand_from test' -l 'showAllCoverage'
complete -c rome -n '__fish_seen_subcommand_from test' -l 'updateSnapshots'
complete -c rome -n '__fish_seen_subcommand_from test' -l 'freezeSnapshots'
complete -c rome -n '__fish_seen_subcommand_from test' -l 'focusAllowed'
complete -c rome -n '__fish_seen_subcommand_from test' -l 'syncTests'
complete -c rome -n '__fish_seen_subcommand_from test' -l 'sourceMaps'
complete -c rome -n '__fish_seen_subcommand_from recover apply' -l 'select'
complete -c rome -n '__fish_seen_subcommand_from rage' -l 'summary'
